# Generated by Django 2.2.7 on 2019-11-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0002_auto_20191113_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_pw',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
