# Generated by Django 2.2.7 on 2019-11-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='messages',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='users',
        ),
    ]
