# Generated by Django 2.2.7 on 2019-11-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_auto_20191114_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login_register_app.User'),
        ),
    ]
