# Generated by Django 2.2.7 on 2019-11-18 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0005_auto_20191118_1446'),
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login_register_app.User'),
            preserve_default=False,
        ),
    ]
