# Generated by Django 2.2.7 on 2019-11-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_trip_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
    ]
