# Generated by Django 2.2.7 on 2019-11-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0004_auto_20191118_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wish_granted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wish_pending',
        ),
    ]
