# Generated by Django 2.2.7 on 2019-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restfull_app', '0003_auto_20191112_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title already exists'}, max_length=255, unique=True),
        ),
    ]
