# Generated by Django 2.2.7 on 2019-11-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0003_auto_20191118_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_granted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_pending',
            field=models.IntegerField(default=0),
        ),
    ]
