# Generated by Django 2.2.7 on 2019-11-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0002_auto_20191113_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_pw',
        ),
    ]
