# Generated by Django 2.2.7 on 2019-11-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0004_auto_20191118_0313'),
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='login_register_app.User')),
                ('wishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wish_app.Wish')),
            ],
        ),
    ]
